import React from "react";
import "./style.css";
import Bear2 from "../../assets/images/bear-2.png";
import Bear3 from "../../assets/images/bear-5.png";
import Bear4 from "../../assets/images/bear-4.png";
import Bear5 from "../../assets/images/bear-3.png";
const Index = () => {
  return (
    <section id="about" className="text-white">
      <div className="container">
        <div class="row align-items-center">
          <div className="col-12 col-md-4 d-none d-md-block">
            <div className="d-flex justify-content-center imageBox">
              <img src={Bear2} alt="" />
            </div>
          </div>
          <div className="col-12 col-md-8 mt-4 mt-sm-0">
            <div className="content-box">
              <h6>What are GoosePunks?</h6>
              <p>
                GoosePunks is a collection of unique NFT avatars. This series is called GoosePunks Renegades Each GoosePunk is algorithmically generated by randomly combining together numerous professionally illustrated properties across various categories. There are more than 1,100 inside the algorithm! When you own a GoosePunk you have full ownership over this character. Ownership of a GoosePunk is your exclusive invitation into the Khena Metaverse. Read more below.
              </p>
            </div>
            <div className="content-box">
              <h6>GoosePunks Lore</h6>
              <p>
                2034. The humans of the planet once called Earth, reach for extraordinary technological heights. During a great time of suspicion and accusation, the world’s governments couldn’t maintain peace. Four mega-nations arm themselves for war. In these days, legends clash and lives are lost. Ground forces are deployed, and they prepare fortifications. What made this war different from the ones before or since? One technician disobeyed orders - not wanting fame, power, or riches, but rather for all of humanity to be obliterated.
              </p>
            </div>
          </div>
        </div>
        <div className="row image-row">
          <div className="col-12 col-sm-4">
            <div className="card-image">
              <img src={Bear3} alt="bear3" />
              <p>11,111 Characters</p>
            </div>
          </div>
          <div className="col-12 col-sm-4">
            <div className="card-image">
              <img src={Bear4} alt="bear3" />
              <p>Randomly Generated</p>
            </div>
          </div>
          <div className="col-12 col-sm-4">
            <div className="card-image">
              <img src={Bear5} alt="bear3" />
              <p>383 Traits</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Index;
